url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Simple Sites Birmingham
email: simplesitesbham@gmail.com
description: "Simple Sites Birmingham is the only complete website management provider in Birmingham. We build, host and maintain simple websites for businesses that value modern design. Don't hire another full-time employee. Hire simple."


# Team names, titles and social links
people:
- name: Robert James
  pic: 4
  position: Owner, Lead Marketer
  social:
    - title: twitter
      url: https://twitter.com/robtherover
    - title: facebook
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/roverbyrobert

- name: Nicole Mubarak
  pic: 6
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/nicolemubarak

- name: Andrew Cartwright
  pic: 5
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/andrewlloydcartwright

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url:
  - title: facebook
    url:
  - title: github
    url: https://github.com/simplesitesbham

# Postal address (add as many lines as necessary)
address:
  - line: 1500 1st Avenue North
  - line: Birmingham, AL 35205

# Build settings
markdown: kramdown
permalink: pretty
