url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Simple Sites Birmingham
email: simplesitesbham@gmail.com
description: "We build, host, and maintain simple websites for businesses that value modern, minimal design. Don't hire another full-time employee. Hire us."


# Team names, titles and social links
people:
- name: Robert James
  pic: 1
  position: Lead Designer, Marketer
  social:
    - title: twitter
      url: # https://twitter.com/robtherover
    - title: facebook
      url: #
    - title: linkedin
      url: # https://www.linkedin.com/in/roverbyrobert

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/simplesitesbham/agency-jekyll-theme

# Postal address (add as many lines as necessary)
address:
  - line: 1500 1st Avenue North
  - line: Birmingham, AL 35205

# Build settings
markdown: kramdown
permalink: pretty
